"""empty message

Revision ID: a96e5b3f6a98
Revises: 
Create Date: 2023-06-16 21:24:17.391060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96e5b3f6a98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('weight_limit', sa.Float(), nullable=False),
    sa.Column('battery_capacity', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('drone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication')
    op.drop_table('drone')
    # ### end Alembic commands ###
